### ISSUE TITLE
Undefined procedure IRAC_OBS_DURATION

### ISSUE THREAD

**Issue by mrmvn** [ingalls91104/IRACSIM#1]
The procedure ***IRAC_OBS_DURATION*** does not seem to be present in the library, nor in the dependencies, is that normal?
It is used both in the procedures *iracsim* and *exoplanets_simulate*.

Running *iracsim.pro* hence crashes with the following message:
**% Attempt to call undefined procedure: 'IRAC_OBS_DURATION'.**

**Comment by ingalls91104** [comment]
Apologies, that is supposed to be present.  I will try to update later today.  Thank you!

Jim

**Comment by ingalls91104** [comment]
Release 1.1.0 should fix this.  Let me know if you run into any other problems.

**Comment by ingalls91104** [comment]
Release 1.1.1 should fix this.  Thanks for catching this.

**Comment by mrmvn** [comment]
Yes, that's fixed, thanks for your reactivity!

Mario
