### ISSUE TITLE
Missing procedures

### ISSUE THREAD

**Issue by mrmvn** [ingalls91104/IRACSIM#2]
I'm facing other missing routines problems, but I'm not sure about the origin of the problem for each of them.
This concerns the use of :
- WHICH in prf_read.pro
- GET_IRAC_PTG_OFFSETS in prf_get_default_astrometry.pro
- POLY_2VAR and SIGN in irac_distort.pro

I bypassed the first issue by replacing the line *WHICH,'PRF_READ',PATH=this_file_loc,/SILENT* by *this_file_loc = FILE_WHICH('iracsim.pro')* (is that correct?), but I am not sure for the 3 other ones.
Is there some other missing files in the package, or may I be missing some dependencies? 

I'm using IDL 8.7.2, and I'm brand new to IDL.

Best regards
Mario

**Comment by ingalls91104** [comment]
Hi Mario,

Yes, I think you are discovering additional missing files.  I’m very sorry about that, I’ll try to get a fix up soon…

Thank you,
Jim

**Comment by ingalls91104** [comment]
I added the missing files.  Thanks for helping debug this!  My IDL_PATH is rather spread out and a few routines fell through the cracks.  Let me know if anything else is missing and I'll try to fix it quickly.

Jim
